### ISSUE TITLE
security for c0-azure-multi-res-group-multi-lb

### ISSUE THREAD

**Issue by svrc-pivotal** [c0-ops/landingpage#6]
HI guys,

Just noting on the c0-azure multi-res-group-multi-lb RefArch, we have all the public apps domain going into cf router and the internal users / system domain getting HAproxy.   any particular reason for this split?  To me it would be the other way around.  Any public facing user can put in whatever Host: header they want including  the system domain.   With HAProxy at least there's the option of host header filtering...

Just filing this here so we can track the convo (happy to jump to email).

**Comment by virtmerlin** [comment]
Thx @svrc-pivotal ,  in reality it matters more for the exact implementation as to wether u need things like advanced ACL's/rewrites etc to where you can make the choice per each customer use case as to what front ends the go-routers or going direct.  For example, u could park OSS-HA-proxy (What the black box is supposed to represent.  Ill add that to the legend of the image as ell), on both paths if u need it.   That said the image should be delivering a 'suggested' path and I'm inclined to agree with ya that the OSS-HA-Proxy route would be more beneficial to default the public facing path and the direct connect to go-routers would be better suited to default to the sys internal traffic,  but in the end this can be architected to meet whatever the specific customer needs wind up being.    Ping me via email if ya wanna go over more ....
